# Generated by Django 5.0.1 on 2024-01-13 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('images', models.IntegerField(default=0)),
                ('new', models.IntegerField(default=0)),
                ('fail', models.IntegerField(default=0)),
                ('error', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('masterpiece', models.IntegerField(default=0)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='references.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticsTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('images', models.IntegerField(default=0)),
                ('new', models.IntegerField(default=0)),
                ('fail', models.IntegerField(default=0)),
                ('error', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('masterpiece', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
