# Generated by Django 5.0.1 on 2024-02-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticstag',
            name='error',
        ),
        migrations.RemoveField(
            model_name='statisticstag',
            name='fail',
        ),
        migrations.RemoveField(
            model_name='statisticstag',
            name='images',
        ),
        migrations.RemoveField(
            model_name='statisticstag',
            name='masterpiece',
        ),
        migrations.RemoveField(
            model_name='statisticstag',
            name='new',
        ),
        migrations.RemoveField(
            model_name='statisticstag',
            name='success',
        ),
        migrations.RemoveField(
            model_name='statisticstotal',
            name='error',
        ),
        migrations.RemoveField(
            model_name='statisticstotal',
            name='fail',
        ),
        migrations.RemoveField(
            model_name='statisticstotal',
            name='images',
        ),
        migrations.RemoveField(
            model_name='statisticstotal',
            name='masterpiece',
        ),
        migrations.RemoveField(
            model_name='statisticstotal',
            name='new',
        ),
        migrations.RemoveField(
            model_name='statisticstotal',
            name='success',
        ),
    ]
